/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSentimentRouteImport } from './routes/_authenticated/sentiment'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedMultiCoinRouteImport } from './routes/_authenticated/multi-coin'
import { Route as AuthenticatedMlEvalRouteImport } from './routes/_authenticated/ml-eval'
import { Route as AuthenticatedLivePricesRouteImport } from './routes/_authenticated/live-prices'
import { Route as AuthenticatedIndicatorsRouteImport } from './routes/_authenticated/indicators'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCandlestickRouteImport } from './routes/_authenticated/candlestick'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAiSignalsRouteImport } from './routes/_authenticated/ai-signals'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSentimentRoute = AuthenticatedSentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMultiCoinRoute = AuthenticatedMultiCoinRouteImport.update({
  id: '/multi-coin',
  path: '/multi-coin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMlEvalRoute = AuthenticatedMlEvalRouteImport.update({
  id: '/ml-eval',
  path: '/ml-eval',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivePricesRoute = AuthenticatedLivePricesRouteImport.update({
  id: '/live-prices',
  path: '/live-prices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicatorsRoute = AuthenticatedIndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandlestickRoute =
  AuthenticatedCandlestickRouteImport.update({
    id: '/candlestick',
    path: '/candlestick',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiSignalsRoute = AuthenticatedAiSignalsRouteImport.update({
  id: '/ai-signals',
  path: '/ai-signals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-signals': typeof AuthenticatedAiSignalsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/candlestick': typeof AuthenticatedCandlestickRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicators': typeof AuthenticatedIndicatorsRoute
  '/live-prices': typeof AuthenticatedLivePricesRoute
  '/ml-eval': typeof AuthenticatedMlEvalRoute
  '/multi-coin': typeof AuthenticatedMultiCoinRoute
  '/news': typeof AuthenticatedNewsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/sentiment': typeof AuthenticatedSentimentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai-signals': typeof AuthenticatedAiSignalsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/candlestick': typeof AuthenticatedCandlestickRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicators': typeof AuthenticatedIndicatorsRoute
  '/live-prices': typeof AuthenticatedLivePricesRoute
  '/ml-eval': typeof AuthenticatedMlEvalRoute
  '/multi-coin': typeof AuthenticatedMultiCoinRoute
  '/news': typeof AuthenticatedNewsRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/sentiment': typeof AuthenticatedSentimentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ai-signals': typeof AuthenticatedAiSignalsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/candlestick': typeof AuthenticatedCandlestickRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/indicators': typeof AuthenticatedIndicatorsRoute
  '/_authenticated/live-prices': typeof AuthenticatedLivePricesRoute
  '/_authenticated/ml-eval': typeof AuthenticatedMlEvalRoute
  '/_authenticated/multi-coin': typeof AuthenticatedMultiCoinRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/sentiment': typeof AuthenticatedSentimentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/ai-signals'
    | '/assistant'
    | '/candlestick'
    | '/dashboard'
    | '/indicators'
    | '/live-prices'
    | '/ml-eval'
    | '/multi-coin'
    | '/news'
    | '/portfolio'
    | '/sentiment'
    | '/settings'
    | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/ai-signals'
    | '/assistant'
    | '/candlestick'
    | '/dashboard'
    | '/indicators'
    | '/live-prices'
    | '/ml-eval'
    | '/multi-coin'
    | '/news'
    | '/portfolio'
    | '/sentiment'
    | '/settings'
    | '/watchlist'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/ai-signals'
    | '/_authenticated/assistant'
    | '/_authenticated/candlestick'
    | '/_authenticated/dashboard'
    | '/_authenticated/indicators'
    | '/_authenticated/live-prices'
    | '/_authenticated/ml-eval'
    | '/_authenticated/multi-coin'
    | '/_authenticated/news'
    | '/_authenticated/portfolio'
    | '/_authenticated/sentiment'
    | '/_authenticated/settings'
    | '/_authenticated/watchlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sentiment': {
      id: '/_authenticated/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof AuthenticatedSentimentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/multi-coin': {
      id: '/_authenticated/multi-coin'
      path: '/multi-coin'
      fullPath: '/multi-coin'
      preLoaderRoute: typeof AuthenticatedMultiCoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ml-eval': {
      id: '/_authenticated/ml-eval'
      path: '/ml-eval'
      fullPath: '/ml-eval'
      preLoaderRoute: typeof AuthenticatedMlEvalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-prices': {
      id: '/_authenticated/live-prices'
      path: '/live-prices'
      fullPath: '/live-prices'
      preLoaderRoute: typeof AuthenticatedLivePricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicators': {
      id: '/_authenticated/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof AuthenticatedIndicatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candlestick': {
      id: '/_authenticated/candlestick'
      path: '/candlestick'
      fullPath: '/candlestick'
      preLoaderRoute: typeof AuthenticatedCandlestickRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-signals': {
      id: '/_authenticated/ai-signals'
      path: '/ai-signals'
      fullPath: '/ai-signals'
      preLoaderRoute: typeof AuthenticatedAiSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiSignalsRoute: typeof AuthenticatedAiSignalsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedCandlestickRoute: typeof AuthenticatedCandlestickRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndicatorsRoute: typeof AuthenticatedIndicatorsRoute
  AuthenticatedLivePricesRoute: typeof AuthenticatedLivePricesRoute
  AuthenticatedMlEvalRoute: typeof AuthenticatedMlEvalRoute
  AuthenticatedMultiCoinRoute: typeof AuthenticatedMultiCoinRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedSentimentRoute: typeof AuthenticatedSentimentRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiSignalsRoute: AuthenticatedAiSignalsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedCandlestickRoute: AuthenticatedCandlestickRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndicatorsRoute: AuthenticatedIndicatorsRoute,
  AuthenticatedLivePricesRoute: AuthenticatedLivePricesRoute,
  AuthenticatedMlEvalRoute: AuthenticatedMlEvalRoute,
  AuthenticatedMultiCoinRoute: AuthenticatedMultiCoinRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedSentimentRoute: AuthenticatedSentimentRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
